name: Validar frontend Vue

on:
  push:
    branches:
      - feature/vue3-modulo2
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Baixar código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Instalar dependências
        run: npm install
      - name: Compilar aplicação
        run: npm run build
