name: Testes Automatizados - Modulo 4

on:
  push:
    branches:
      - feature/testes-modulo4
  workflow_dispatch:

jobs:
  testes:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front-end

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Executar testes automatizados
        run: npm test
